name: 'Eastplayer CICD action'
description: 'Lorem ipsum'
runs:
  using: "composite"
  steps:
    - name: Set GitHub Path
      run: echo "$GITHUB_ACTION_PATH" >> $GITHUB_PATH
      shell: bash
      env:
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    - name: Run cicd.sh
      run: cicd.sh
      shell: bash
